### ISSUE TITLE
各団体個別ページの編集方法 クラ代向けの説明書

### ISSUE THREAD

**Issue by ekkekuru2** [hibiya-itchief/quaint-docs#16]

**Comment by thoth333** [comment]
ほんとに些細なんですけど、
![image](https://github.com/hibiya-itchief/quaint-docs/assets/128669695/2f1399d6-6aba-4dd0-827a-316c88628998)
マイクロソフトアカウント"に"ログイン
にしたくなっちゃって…

あと、
![image](https://github.com/hibiya-itchief/quaint-docs/assets/128669695/6b7a17e5-6b2a-45a0-aa20-a909f9c4959d)
ownerじゃわかりづらいか、ってことで「団体代表者」と表示されるようになる予定です
(すみません今まだその機能できてません)

なのでその２点、できれば変えていただきたいです

**Comment by ekkekuru2** [comment]
@aozoraUS お願いしても良いですか
